"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

const translations = {
  en: {
    title: "Flood Monitoring System",
    subtitles: {
      overview: "Monitor current water levels and affected area based on reports.",
      analytics: "View weekly insights and analyze water level history.",
      weather: "Check real-time weather and forecasts. we get data from Thai Meteorological Department (TMD).",
      community: "Help us report flood and affected area or just chat with others.",
    },
    tabs: {
      overview: "Now",
      analytics: "Insights",
      weather: "Weather",
      community: "Community",
    },
    tabstitle: {
      overview: "Now",
      analytics: "Insights",
      weather: "Weather & Forecast",
      community: "Community & Reports",
    },
    cards: {
      currentLevel: "Lastest water-reading data",
      trend: "Trend",
      timeToWarning: "ETA to Flood Warning Level",
      timeToDanger: "ETA to Critical Level",
      criticalReached: "Critical level reached",
      lastUpdate: "Last Update",
      stable: "Unable to calculate. Water level isn't rising",
      trendDescription: "Based on last 12 data (1 hour)",
      timeToWarningDescription: "At current rate",
      realTime: "Real-time data",
      noData: "No data",
      connectionLost: "Connection lost",
      sensor: "Sensor",
      dataSource: "Data Source",
      website: "Website Data",
      community: "Community Reports",
      combined: "Combined Data",
      refreshData: "Refresh Data",
      zoomIn: "Zoom In",
      zoomOut: "Zoom Out",
      resetZoom: "Reset Zoom",
    },
    status: {
      normal: "Safe",
      warning: "Unsafe",
      danger: "Critical",
      waterLevel: "Water level is",
      goodMorning: "Good morning!",
      goodAfternoon: "Good afternoon!",
      goodEvening: "Good evening!",
      goodNight: "Good night!",
      weatherGood: "and the weather looks good at",
      notRaining: "with no rain",
      raining: "with rain",
    },
    trends: {
      rising: "Rising",
      falling: "Receding",
      stable: "Stable",
      ratePerHour: "cm/hr",
    },
    chart: {
      title: "Water Level Over Time",
      description: "Real-time flood level measurements",
      yAxisLabel: "Water Level (cm)",
      waterLevel: "Water Level",
      dangerLevel: "Critical",
      warningLevel: "Attention need",
      last24Hours: "Last 24 Hours",
      lastWeek: "Last Week",
      compareData: "Compare Data",
    },
    analytics: {
      dailyAverage: "Daily Average",
      dailyAverageDescription: "Average level today",
      peakLevel: "Peak Level",
      peakLevelDescription: "Highest level today",
      weeklyTrend: "Weekly Trend",
      dataComparison: "Data Comparison",
      lastDay: "Last Day",
      lastWeek: "Last Week",
      pastData: "Past Data",
      selectDateRange: "Select Date Range",
    },
    weather: {
      title: "Weather Forecast",
      current: "Current Weather",
      forecast: "5-Day Forecast",
      hourlyForecast: "3-Hour Forecast",
      forecastDescription: "Weather conditions that may affect flood levels",
      noData: "Weather data unavailable",
      weatherMap: "Weather Map",
      showMap: "Show Weather Map",
      hideMap: "Hide Weather Map",
    },
    community: {
      title: "Community Reports",
      chat: "Community Chat",
      signIn: "Sign In",
      signUp: "Sign Up",
      signOut: "Sign Out",
      email: "Email",
      password: "Password",
      username: "Username",
      createAccount: "Create Account",
      onlineUsers: "online user",
      offlineUsers: "offline user",
      typing: "is typing...",
      sendMessage: "Send Message",
      reply: "Reply",
      like: "Like",
      dislike: "Dislike",
      vote: "Vote",
      isRaining: "Is it raining in StreePasertSin School?",
      yes: "Yes",
      no: "No",
      affectedAreas: "Affected Areas",
      reportCondition: "Report Current Condition",
      emailDomain: "Only @streetrat.ac.th emails are allowed",
      scrollToBottom: "Scroll to bottom",
    },
    developer: {
      title: "Developer Settings",
      passwordRequired: "Enter password to access developer settings",
      password: "Password",
      enterPassword: "Enter password",
      authenticate: "Authenticate",
      accessGranted: "Access Granted",
      accessGrantedDescription: "You can now modify settings",
      accessDenied: "Access Denied",
      accessDeniedDescription: "Incorrect password",
      settings: "Developer Settings",
      settingsDescription: "Configure API keys and system parameters",
      affectedAreasConfig: "Affected Areas Configuration",
      affectedAreasDescription: "Configure water levels for different affected areas",
      areaName: "Area Name",
      waterLevel: "Water Level (cm)",
      addArea: "Add Area",
      removeArea: "Remove Area",
      announcement: {
        title: "Announcement System",
        description: "Send announcements to all users",
        message: "Announcement Message",
        placeholder: "Enter your announcement message...",
        note: "This message will be shown to all users",
        clear: "Clear Announcements",
      },
      waterLevelSettings: "Flood Level Configuration",
      waterLevelSettingsDescription: "Configure flood warning levels and update intervals",
      warningLevel: "Unsafe Level (cm)",
      dangerLevel: "Critical Level (cm)",
      updateInterval: "Update Interval (seconds)",
      cancel: "Cancel",
      saveSettings: "Save Settings",
      settingsSaved: "Settings Saved",
      settingsSavedDescription: "Configuration has been updated",
      developerOnlyWarning: {
        title: "Developer Access Only",
        description: "This section is restricted to authorized developers only.",
      },
      turnstileVerificationFailed: "Please complete the verification",
    },
    timeUnits: {
      days: "days",
      hours: "hours",
      minutes: "minutes",
    },
    common: {
      loading: "Loading...",
      error: "Error",
      retry: "Retry",
      close: "Close",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      remove: "Remove",
      darkMode: "Dark Mode",
      lightMode: "Light Mode",
      addLineContact: "Add us to recieve flood warning",
    },
    affectedAreas: {
      title: "Affected Areas Report",
      description: "Areas with recent flood reports (last 24 hours)",
      loading: "Loading affected areas...",
      noAreas: "No affected areas configured",
      threshold: "Threshold:",
      report: "report",
      reports: "reports",
      inLast24h: "in last 24h",
      latestStatus: "Latest status:",
      noReports: "No reports - area appears safe",
      activityLevel: "Activity level",
    },
    floodReport: {
      title: "Flood Report System",
      signInPrompt: "Sign in to the community chat to report flood conditions.",
      reportTitle: "Report Flood Condition",
      reportDescription: "Help the community by reporting flood conditions in your area",
      selectArea: "Select Affected Area",
      chooseArea: "Choose an area",
      severityLevel: "Severity Level",
      severityLow: "Low - Minor flooding",
      severityModerate: "Moderate - Some water accumulation",
      severityHigh: "High - Significant flooding",
      severityCritical: "Critical - Severe flooding",
      description: "Description",
      descriptionPlaceholder: "Describe the flooding conditions, water depth, affected structures, etc.",
      submitting: "Submitting...",
      submitReport: "Submit Report",
      recentReports: "Recent Reports",
      recentReportsDescription: "Latest flood reports from the community",
      noReports: "No flood reports yet",
      submitSuccess: "Report submitted successfully!",
      fillAllFields: "Please fill in all fields",
      submitFailed: "Failed to submit report",
      alreadyReported: "You have already reported on this area in the last 24 hours.",
    },
    system: {
      online: "Online",
      offline: "Offline",
      connected: "Connected",
      disconnected: "Disconnected",
      active: "Active",
      inactive: "Inactive",
      testing: "Testing...",
      testConnection: "Test Connection",
      systemStatus: "System Status",
      databaseConnection: "Database Connection",
      databaseHealth: "Database connection and system health",
      lastDataUpdate: "Last Data Update",
      lastUpdate: "Last update:",
      realTimeUpdates: "Real-time Updates",
      minutesAgo: "m ago",
      hoursAgo: "h ago",
      daysAgo: "d ago",
    },
    alerts: {
      sensorStale: "sensors is not sending new data for {minutes} minutes. data below are the last data sensor sent.",
    },
    precipitation: {
      title: "Current Precipitation",
      status: "Current Precipitation Status",
      active: "Active",
      dry: "Dry",
      noData: "No precipitation data available",
      lastHour: "Rain in the last hour",
      lastThreeHours: "Rain in the last 3 hours",
      intensity: {
        none: "No Rain",
        light: "Light Rain",
        moderate: "Moderate Rain",
        heavy: "Heavy Rain",
        extreme: "Extreme Rain",
      },
      floodRisk: {
        title: "Flood Risk Assessment",
        none: "No immediate flood risk",
        low: "Low flood risk - Monitor conditions",
        moderate: "Moderate flood risk - Stay alert",
        high: "High flood risk - Take precautions",
      },
      snow: {
        title: "Snow Conditions",
        lastHour: "in last hour",
        lastThreeHours: "in last 3 hours",
      },
      guidelines: {
        title: "Precipitation Guidelines",
        light: "Light (0.1-2.5mm/h)",
        lightDesc: "Minimal impact",
        moderate: "Moderate (2.5-10mm/h)",
        moderateDesc: "Possible ponding",
        heavy: "Heavy (10-50mm/h)",
        heavyDesc: "Flooding likely",
        extreme: "Extreme (>50mm/h)",
        extremeDesc: "Severe flooding",
      },
    },
    weatherVote: {
      title: "Weather Report",
      pleaseWait: "Please wait...",
      description: "It looks like it might be raining. Can you confirm the weather at StreePasertSin School?",
      confirmRain: "Raining",
      confirmNoRain: "No Rain",
      iDontKnow: "I don't know / Not sure",
      footer: "Your report helps the community track flood risks.",
      thankYou: "Thank you for your report!",
      alreadyVoted: "You have already voted recently.",
      error: "Failed to submit vote. Please try again.",
      communityReport: "Is it raining? Community Report",
      votes: "all votes in the last 30m",
      yes: "Yes",
      no: "No",
    },
  },
  th: {
    title: "ระบบตรวจสอบน้ำท่วม",
    subtitles: {
      overview: "ตรวจสอบระดับน้ำและพื้นที่ได้รับผลกระทบจากการรายงานจากคนอื่นในปัจจุบัน.",
      analytics: "ตรวจสอบระดับน้ำรายสัปดาห์และวิเคราห์ระดับน้ำในอดีต",
      weather: "สภาพอากาศปัจจุบันและการพยากรณ์บริการโดย กรมอุตุนิยมวิทยา",
      community: "ช่วยรายงานน้ำท่วมหรือพื้นที่ที่ได้รับผบกระทบและพูดคุยกับคนอื่น",
    },
    tabs: {
      overview: "ตอนนี้",
      analytics: "ข้อมุลวิเคราะห์",
      weather: "สภาพอากาศ",
      community: "ชุมชน",
    },
    tabstitle: {
      overview: "ตอนนี้",
      analytics: "ข้อมุลวิเคราะห์",
      weather: "สภาพอากาศและการพยากรณ์",
      community: "ชุมชนและการรายงาน",
    },
    cards: {
      currentLevel: "ระดับน้ำล่าสุด",
      trend: "แนวโน้ม",
      timeToWarning: "เวลาจนกว่าจะถึงระดับเฝ้าระวัง",
      timeToDanger: "เวลาจนกว่าจะถึงระดับวิกฤติ",
      criticalReached: "ถึงระดับวิกฤติแล้ว",
      lastUpdate: "อัปเดตล่าสุด",
      stable: "คำนวณไม่ได้ ระดับน้ำไม่ได้สูงขึ้น",
      trendDescription: "จากข้อมูล 12 ครั้งล่าสุด (1 ชั่วโมง)",
      timeToWarningDescription: "ในอัตราปัจจุบัน",
      realTime: "ข้อมูลเรียลไทม์",
      noData: "ไม่มีข้อมูล",
      connectionLost: "การเชื่อมต่อขาดหาย",
      sensor: "เซ็นเซอร์",
      dataSource: "แหล่งข้อมูล",
      website: "ข้อมูลเว็บไซต์",
      community: "รายงานชุมชน",
      combined: "ข้อมูลรวม",
      refreshData: "รีเฟรชข้อมูล",
      zoomIn: "ขยายเข้า",
      zoomOut: "ขยายออก",
      resetZoom: "รีเซ็ตการขยาย",
    },
    status: {
      normal: "ปลอดภัย",
      warning: "เฝ้าระวัง",
      danger: "วิกฤติ",
      waterLevel: "ระดับน้ำ",
      goodMorning: "สวัสดีตอนเช้า!",
      goodAfternoon: "สวัสดีตอนบ่าย!",
      goodEvening: "สวัสดีตอนเย็น!",
      goodNight: "สวัสดีตอนกลางคืน!",
      weatherGood: "และสภาพอากาศดีที่",
      notRaining: "และไม่มีฝนตก",
      raining: "และมีฝนตก",
    },
    trends: {
      rising: "เพิ่มขึ้น",
      falling: "ลดลง",
      stable: "คงที่",
      ratePerHour: "ซม./ชม.",
    },
    chart: {
      title: "ระดับน้ำตามเวลา",
      description: "การวัดระดับน้ำท่วมแบบเรียลไทม์",
      yAxisLabel: "ระดับน้ำ (ซม.)",
      waterLevel: "ระดับน้ำ",
      dangerLevel: "ระดับวิกฤติ",
      warningLevel: "ระดับเฝ้าระวัง",
      last24Hours: "24 ชั่วโมงที่ผ่านมา",
      lastWeek: "สัปดาห์ที่ผ่านมา",
      compareData: "เปรียบเทียบข้อมูล",
    },
    analytics: {
      dailyAverage: "ค่าเฉลี่ยรายวัน",
      dailyAverageDescription: "ค่าเฉลี่ยระดับวันนี้",
      peakLevel: "ระดับสูงสุด",
      peakLevelDescription: "ระดับสูงสุดวันนี้",
      weeklyTrend: "แนวโน้มรายสัปดาห์",
      dataComparison: "เปรียบเทียบข้อมูล",
      lastDay: "วันที่ผ่านมา",
      lastWeek: "สัปดาห์ที่ผ่านมา",
      pastData: "ข้อมูลในอดีต",
      selectDateRange: "เลือกช่วงเวลา",
    },
    weather: {
      title: "พยากรณ์อากาศ",
      current: "สภาพอากาศปัจจุบัน",
      forecast: "พยากรณ์ 5 วัน",
      hourlyForecast: "พยากรณ์ 3 ชั่วโมง",
      forecastDescription: "สภาพอากาศที่อาจส่งผลต่อระดับน้ำท่วม",
      noData: "ไม่มีข้อมูลสภาพอากาศ",
      weatherMap: "แผนที่สภาพอากาศ",
      showMap: "แสดงแผนที่สภาพอากาศ",
      hideMap: "ซ่อนแผนที่สภาพอากาศ",
    },
    community: {
      title: "รายงานชุมชน",
      chat: "แชทชุมชน",
      signIn: "เข้าสู่ระบบ",
      signUp: "สมัครสมาชิก",
      signOut: "ออกจากระบบ",
      email: "อีเมล",
      password: "รหัสผ่าน",
      username: "ชื่อผู้ใช้",
      createAccount: "สร้างบัญชี",
      onlineUsers: "ผู้ใช้ออนไลน์",
      offlineUsers: "ผู้ใช้ออฟไลน์",
      typing: "กำลังพิมพ์...",
      sendMessage: "ส่งข้อความ",
      reply: "ตอบกลับ",
      like: "ถูกใจ",
      dislike: "ไม่ถูกใจ",
      vote: "โหวต",
      isRaining: "ฝนตกในพื้นที่ของคุณหรือไม่?",
      yes: "ใช่",
      no: "ไม่",
      affectedAreas: "พื้นที่ได้รับผลกระทบ",
      reportCondition: "รายงานสภาพปัจจุบัน",
      emailDomain: "อนุญาตเฉพาะอีเมล @streetrat.ac.th เท่านั้น",
      scrollToBottom: "เลื่อนลงล่างสุด",
    },
    developer: {
      title: "การตั้งค่านักพัฒนา",
      passwordRequired: "ใส่รหัสผ่านเพื่อเข้าถึงการตั้งค่านักพัฒนา",
      password: "รหัสผ่าน",
      enterPassword: "ใส่รหัสผ่าน",
      authenticate: "ยืนยันตัวตน",
      accessGranted: "เข้าถึงได้",
      accessGrantedDescription: "คุณสามารถแก้ไขการตั้งค่าได้แล้ว",
      accessDenied: "ปฏิเสธการเข้าถึง",
      accessDeniedDescription: "รหัสผ่านไม่ถูกต้อง",
      settings: "การตั้งค่านักพัฒนา",
      settingsDescription: "กำหนดค่า API keys และพารามิเตอร์ระบบ",
      affectedAreasConfig: "การกำหนดค่าพื้นที่ได้รับผลกระทบ",
      affectedAreasDescription: "กำหนดระดับน้ำสำหรับพื้นที่ได้รับผลกระทบต่างๆ",
      areaName: "ชื่อพื้นที่",
      waterLevel: "ระดับน้ำ (ซม.)",
      addArea: "เพิ่มพื้นที่",
      removeArea: "ลบพื้นที่",
      announcement: {
        title: "ระบบประกาศ",
        description: "ส่งประกาศให้ผู้ใช้ทุกคน",
        message: "ข้อความประกาศ",
        placeholder: "ใส่ข้อความประกาศของคุณ...",
        note: "ข้อความนี้จะแสดงให้ผู้ใช้ทุกคนเห็น",
        clear: "ล้างประกาศ",
      },
      waterLevelSettings: "การกำหนดค่าระดับน้ำท่วม",
      waterLevelSettingsDescription: "กำหนดระดับเตือนน้ำท่วมและช่วงเวลาอัปเดต",
      warningLevel: "ระดับเฝ้าระวัง (ซม.)",
      dangerLevel: "ระดับวิกฤติ (ซม.)",
      updateInterval: "ช่วงเวลาอัปเดต (วินาที)",
      cancel: "ยกเลิก",
      saveSettings: "บันทึกการตั้งค่า",
      settingsSaved: "บันทึกการตั้งค่าแล้ว",
      settingsSavedDescription: "การกำหนดค่าได้รับการอัปเดตแล้ว",
      developerOnlyWarning: {
        title: "เฉพาะนักพัฒนาเท่านั้น",
        description: "ส่วนนี้จำกัดเฉพาะนักพัฒนาที่ได้รับอนุญาตเท่านั้น",
      },
      turnstileVerificationFailed: "กรุณาทำการยืนยันให้เสร็จสิ้น",
    },
    timeUnits: {
      days: "วัน",
      hours: "ชั่วโมง",
      minutes: "นาที",
    },
    common: {
      loading: "โหลดอยู่รอแป๊ป...",
      error: "ข้อผิดพลาด",
      retry: "ลองใหม่",
      close: "ปิด",
      save: "บันทึก",
      cancel: "ยกเลิก",
      delete: "ลบ",
      edit: "แก้ไข",
      add: "เพิ่ม",
      remove: "ลบ",
      darkMode: "โหมดมืด",
      lightMode: "โหมดสว่าง",
      addLineContact: "แอดเพื่อรับการเตือนน้ำท่วม",
    },
    affectedAreas: {
      title: "รายงานพื้นที่ได้รับผลกระทบ",
      description: "พื้นที่ที่มีรายงานน้ำท่วมล่าสุด (24 ชั่วโมงที่ผ่านมา)",
      loading: "กำลังโหลดพื้นที่ได้รับผลกระทบ...",
      noAreas: "ยังไม่มีการกำหนดพื้นที่ได้รับผลกระทบ",
      threshold: "เกณฑ์:",
      report: "รายงาน",
      reports: "รายงาน",
      inLast24h: "ใน 24 ชั่วโมงที่ผ่านมา",
      latestStatus: "สถานะล่าสุด:",
      noReports: "ไม่มีรายงาน - พื้นที่ดูปลอดภัย",
      activityLevel: "ระดับกิจกรรม",
    },
    floodReport: {
      title: "ระบบรายงานน้ำท่วม",
      signInPrompt: "เข้าสู่ระบบแชทชุมชนเพื่อรายงานสภาพน้ำท่วม",
      reportTitle: "รายงานสภาพน้ำท่วม",
      reportDescription: "ช่วยเหลือชุมชนโดยรายงานสภาพน้ำท่วมในพื้นที่ของคุณ",
      selectArea: "เลือกพื้นที่ได้รับผลกระทบ",
      chooseArea: "เลือกพื้นที่",
      severityLevel: "ระดับความรุนแรง",
      severityLow: "ต่ำ - น้ำท่วมเล็กน้อย",
      severityModerate: "ปานกลาง - มีน้ำขังบ้าง",
      severityHigh: "สูง - น้ำท่วมมาก",
      severityCritical: "วิกฤต - น้ำท่วมรุนแรง",
      description: "รายละเอียด",
      descriptionPlaceholder: "อธิบายสภาพน้ำท่วม ความลึกของน้ำ โครงสร้างที่ได้รับผลกระทบ ฯลฯ",
      submitting: "กำลังส่ง...",
      submitReport: "ส่งรายงาน",
      recentReports: "รายงานล่าสุด",
      recentReportsDescription: "รายงานน้ำท่วมล่าสุดจากชุมชน",
      noReports: "ยังไม่มีรายงานน้ำท่วม",
      submitSuccess: "ส่งรายงานสำเร็จ!",
      fillAllFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
      submitFailed: "ส่งรายงานไม่สำเร็จ",
      alreadyReported: "คุณได้รายงานเกี่ยวกับพื้นที่นี้ไปแล้วใน 24 ชั่วโมงที่ผ่านมา",
    },
    system: {
      online: "ออนไลน์",
      offline: "ออฟไลน์",
      connected: "เชื่อมต่อแล้ว",
      disconnected: "การเชื่อมต่อขาดหาย",
      active: "ใช้งาน",
      inactive: "ไม่ใช้งาน",
      testing: "กำลังทดสอบ...",
      testConnection: "ทดสอบการเชื่อมต่อ",
      systemStatus: "สถานะระบบ",
      databaseConnection: "การเชื่อมต่อฐานข้อมูล",
      databaseHealth: "การเชื่อมต่อฐานข้อมูลและสุขภาพระบบ",
      lastDataUpdate: "อัปเดตข้อมูลล่าสุด",
      lastUpdate: "อัปเดตล่าสุด:",
      realTimeUpdates: "การอัปเดตแบบเรียลไทม์",
      minutesAgo: "นาทีที่แล้ว",
      hoursAgo: "ชั่วโมงที่แล้ว",
      daysAgo: "วันที่แล้ว",
    },
    alerts: {
      sensorStale: "เซ็นเซอร์ไม่มีการส่งข้อมูลใหม่มาเป็นเวลา {minutes} นาที ข้อมูลด้านล่างเป็นข้อมูลครั้งสุดท้ายที่เซ็นเซอร์ส่งมา",
    },
    precipitation: {
      title: "ปริมาณฝนปัจจุบัน",
      status: "สถานะปริมาณฝนปัจจุบัน",
      active: "มีฝน",
      dry: "แห้ง",
      noData: "ไม่มีข้อมูลปริมาณฝน",
      lastHour: "ปริมาณฝนในชั่วโมงที่ผ่านมา",
      lastThreeHours: "ปริมาณฝนใน 3 ชั่วโมงที่ผ่านมา",
      intensity: {
        none: "ไม่มีฝน",
        light: "ฝนเบา",
        moderate: "ฝนปานกลาง",
        heavy: "ฝนหนัก",
        extreme: "ฝนหนักมาก",
      },
      floodRisk: {
        title: "การประเมินความเสี่ยงน้ำท่วม",
        none: "ไม่มีความเสี่ยงน้ำท่วมในทันที",
        low: "ความเสี่ยงน้ำท่วมต่ำ - ติดตามสถานการณ์",
        moderate: "ความเสี่ยงน้ำท่วมปานกลาง - ระมัดระวัง",
        high: "ความเสี่ยงน้ำท่วมสูง - เตรียมมาตรการป้องกัน",
      },
      snow: {
        title: "สภาพหิมะ",
        lastHour: "ในชั่วโมงที่ผ่านมา",
        lastThreeHours: "ใน 3 ชั่วโมงที่ผ่านมา",
      },
      guidelines: {
        title: "แนวทางปริมาณฝน",
        light: "เบา (0.1-2.5มม./ชม.)",
        lightDesc: "ผลกระทบน้อย",
        moderate: "ปานกลาง (2.5-10มม./ชม.)",
        moderateDesc: "อาจมีน้ำขัง",
        heavy: "หนัก (10-50มม./ชม.)",
        heavyDesc: "มีแนวโน้มน้ำท่วม",
        extreme: "หนักมาก (>50มม./ชม.)",
        extremeDesc: "น้ำท่วมรุนแรง",
      },
    },
    weatherVote: {
      title: "รายงานสภาพอากาศ",
      pleaseWait: "กรุณารอสักครู่...",
      description: "ดูเหมือนว่าฝนอาจจะกำลังตก ช่วยยืนยันสภาพอากาศในโรงเรียนสตรีประเสริฐศิลป์หน่อย",
      confirmRain: "ฝนตก",
      confirmNoRain: "ฝนไม่ตก",
      iDontKnow: "ไม่แน่ใจ / ไม่ทราบ",
      footer: "รายงานของคุณช่วยให้ชุมชนติดตามความเสี่ยงน้ำท่วม",
      thankYou: "ขอบคุณสำหรับรายงานของคุณ!",
      alreadyVoted: "คุณได้โหวตไปแล้วเมื่อเร็วๆ นี้",
      error: "ส่งรายงานไม่สำเร็จ กรุณาลองใหม่",
      communityReport: "ฝนตกไหม? รายงานจากชุมชน",
      votes: "โหวต / 30นาที",
      yes: "ใช่",
      no: "ไม่ใช่",
    },
  },
}

interface LanguageContextType {
  language: "en" | "th"
  setLanguage: (lang: "en" | "th") => void
  t: typeof translations.en
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<"en" | "th">("th")

  useEffect(() => {
    // Load saved language preference
    const savedLanguage = localStorage.getItem("language") as "en" | "th"
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "th")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: "en" | "th") => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const value = {
    language,
    setLanguage: handleSetLanguage,
    t: translations[language],
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
