"use client"

const translations = {
  en: {
    title: "Flood Monitoring System",
    subtitle: "Real-time flood level monitoring for school safety",
    tabs: {
      overview: "Overview",
      analytics: "Analytics",
      weather: "Weather",
      community: "Community",
    },
    cards: {
      currentLevel: "Current Water Level",
      trend: "Trend",
      timeToWarning: "Time to Flood Warning",
      lastUpdate: "Last Update",
      stable: "Stable",
      trendDescription: "Based on last 5 readings",
      timeToWarningDescription: "At current rate",
      realTime: "Real-time data",
      dataSource: "Data Source",
      website: "Website Data",
      community: "Community Reports",
      combined: "Combined Data",
      refreshData: "Refresh Data",
      zoomIn: "Zoom In",
      zoomOut: "Zoom Out",
      resetZoom: "Reset Zoom",
    },
    status: {
      normal: "Safe",
      warning: "Flood Watch",
      danger: "Flood Warning",
      goodMorning: "Good morning! The water level looks okay",
      goodAfternoon: "Good afternoon! The water level looks okay",
      goodEvening: "Good evening! The water level looks okay",
      goodNight: "Good night! The water level looks okay",
      weatherGood: "and the weather looks good at",
      notRaining: "and not raining",
      raining: "and it's raining",
    },
    trends: {
      rising: "Rising",
      falling: "Receding",
      stable: "Stable",
      ratePerHour: "cm/hr",
    },
    chart: {
      title: "Water Level Over Time",
      description: "Real-time flood level measurements",
      yAxisLabel: "Water Level (cm)",
      waterLevel: "Water Level",
      dangerLevel: "Flood Warning Level",
      warningLevel: "Flood Watch Level",
      last24Hours: "Last 24 Hours",
      lastWeek: "Last Week",
      compareData: "Compare Data",
    },
    analytics: {
      dailyAverage: "Daily Average",
      dailyAverageDescription: "Average level today",
      peakLevel: "Peak Level",
      peakLevelDescription: "Highest level today",
      weeklyTrend: "Weekly Trend",
      dataComparison: "Data Comparison",
      lastDay: "Last Day",
      lastWeek: "Last Week",
    },
    weather: {
      title: "Weather Forecast",
      current: "Current Weather",
      forecast: "5-Day Forecast",
      hourlyForecast: "3-Hour Forecast",
      forecastDescription: "Weather conditions that may affect flood levels",
      noData: "Weather data unavailable",
      weatherMap: "Weather Map",
      showMap: "Show Weather Map",
      hideMap: "Hide Weather Map",
    },
    community: {
      title: "Community Reports",
      chat: "Community Chat",
      signIn: "Sign In",
      signUp: "Sign Up",
      signOut: "Sign Out",
      email: "Email",
      password: "Password",
      username: "Username",
      createAccount: "Create Account",
      onlineUsers: "Online Users",
      offlineUsers: "Offline Users",
      typing: "is typing...",
      sendMessage: "Send Message",
      reply: "Reply",
      like: "Like",
      dislike: "Dislike",
      vote: "Vote",
      isRaining: "Is it raining in your area?",
      yes: "Yes",
      no: "No",
      affectedAreas: "Affected Areas",
      reportCondition: "Report Current Condition",
      emailDomain: "Only @satreetrat.ac.th emails are allowed",
    },
    developer: {
      title: "Developer Settings",
      passwordRequired: "Enter password to access developer settings",
      password: "Password",
      enterPassword: "Enter password",
      authenticate: "Authenticate",
      accessGranted: "Access Granted",
      accessGrantedDescription: "You can now modify settings",
      accessDenied: "Access Denied",
      accessDeniedDescription: "Incorrect password",
      settings: "Developer Settings",
      settingsDescription: "Configure API keys and system parameters",
      affectedAreasConfig: "Affected Areas Configuration",
      affectedAreasDescription: "Configure water levels for different affected areas",
      areaName: "Area Name",
      waterLevel: "Water Level (cm)",
      addArea: "Add Area",
      removeArea: "Remove Area",
      announcement: {
        title: "Announcement System",
        description: "Send announcements to all users",
        message: "Announcement Message",
        placeholder: "Enter your announcement message...",
        note: "This message will be shown to all users",
        clear: "Clear Announcements",
      },
      waterLevelSettings: "Flood Level Configuration",
      waterLevelSettingsDescription: "Configure flood warning levels and update intervals",
      warningLevel: "Flood Watch Level (cm)",
      dangerLevel: "Flood Warning Level (cm)",
      updateInterval: "Update Interval (seconds)",
      cancel: "Cancel",
      saveSettings: "Save Settings",
      settingsSaved: "Settings Saved",
      settingsSavedDescription: "Configuration has been updated",
    },
    timeUnits: {
      days: "days",
      hours: "hours",
      minutes: "minutes",
    },
    common: {
      loading: "Loading...",
      error: "Error",
      retry: "Retry",
      close: "Close",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      remove: "Remove",
      darkMode: "Dark Mode",
      lightMode: "Light Mode",
      addLineContact: "Add LINE Contact",
    },
  },
  th: {
    title: "ระบบตรวจสอบน้ำท่วม",
    subtitle: "ระบบตรวจสอบระดับน้ำแบบเรียลไทม์เพื่อความปลอดภัยของโรงเรียน",
    tabs: {
      overview: "ภาพรวม",
      analytics: "การวิเคราะห์",
      weather: "สภาพอากาศ",
      community: "ชุมชน",
    },
    cards: {
      currentLevel: "ระดับน้ำปัจจุบัน",
      trend: "แนวโน้ม",
      timeToWarning: "เวลาถึงการเตือนน้ำท่วม",
      lastUpdate: "อัปเดตล่าสุด",
      stable: "คงที่",
      trendDescription: "จากข้อมูล 5 ครั้งล่าสุด",
      timeToWarningDescription: "ในอัตราปัจจุบัน",
      realTime: "ข้อมูลเรียลไทม์",
      dataSource: "แหล่งข้อมูล",
      website: "ข้อมูลเว็บไซต์",
      community: "รายงานชุมชน",
      combined: "ข้อมูลรวม",
      refreshData: "รีเฟรชข้อมูล",
      zoomIn: "ขยายเข้า",
      zoomOut: "ขยายออก",
      resetZoom: "รีเซ็ตการขยาย",
    },
    status: {
      normal: "ปลอดภัย",
      warning: "เฝ้าระวังน้ำท่วม",
      danger: "เตือนน้ำท่วม",
      goodMorning: "สวัสดีตอนเช้า! ระดับน้ำดูปกติดี",
      goodAfternoon: "สวัสดีตอนบ่าย! ระดับน้ำดูปกติดี",
      goodEvening: "สวัสดีตอนเย็น! ระดับน้ำดูปกติดี",
      goodNight: "สวัสดีตอนกลางคืน! ระดับน้ำดูปกติดี",
      weatherGood: "และสภาพอากาศดีที่",
      notRaining: "และไม่มีฝนตก",
      raining: "และมีฝนตก",
    },
    trends: {
      rising: "เพิ่มขึ้น",
      falling: "ลดลง",
      stable: "คงที่",
      ratePerHour: "ซม./ชม.",
    },
    chart: {
      title: "ระดับน้ำตามเวลา",
      description: "การวัดระดับน้ำท่วมแบบเรียลไทม์",
      yAxisLabel: "ระดับน้ำ (ซม.)",
      waterLevel: "ระดับน้ำ",
      dangerLevel: "ระดับเตือนน้ำท่วม",
      warningLevel: "ระดับเฝ้าระวังน้ำท่วม",
      last24Hours: "24 ชั่วโมงที่ผ่านมา",
      lastWeek: "สัปดาห์ที่ผ่านมา",
      compareData: "เปรียบเทียบข้อมูล",
    },
    analytics: {
      dailyAverage: "ค่าเฉลี่ยรายวัน",
      dailyAverageDescription: "ค่าเฉลี่ยระดับวันนี้",
      peakLevel: "ระดับสูงสุด",
      peakLevelDescription: "ระดับสูงสุดวันนี้",
      weeklyTrend: "แนวโน้มรายสัปดาห์",
      dataComparison: "เปรียบเทียบข้อมูล",
      lastDay: "วันที่ผ่านมา",
      lastWeek: "สัปดาห์ที่ผ่านมา",
    },
    weather: {
      title: "พยากรณ์อากาศ",
      current: "สภาพอากาศปัจจุบัน",
      forecast: "พยากรณ์ 5 วัน",
      hourlyForecast: "พยากรณ์ 3 ชั่วโมง",
      forecastDescription: "สภาพอากาศที่อาจส่งผลต่อระดับน้ำท่วม",
      noData: "ไม่มีข้อมูลสภาพอากาศ",
      weatherMap: "แผนที่สภาพอากาศ",
      showMap: "แสดงแผนที่สภาพอากาศ",
      hideMap: "ซ่อนแผนที่สภาพอากาศ",
    },
    community: {
      title: "รายงานชุมชน",
      chat: "แชทชุมชน",
      signIn: "เข้าสู่ระบบ",
      signUp: "สมัครสมาชิก",
      signOut: "ออกจากระบบ",
      email: "อีเมล",
      password: "รหัสผ่าน",
      username: "ชื่อผู้ใช้",
      createAccount: "สร้างบัญชี",
      onlineUsers: "ผู้ใช้ออนไลน์",
      offlineUsers: "ผู้ใช้ออฟไลน์",
      typing: "กำลังพิมพ์...",
      sendMessage: "ส่งข้อความ",
      reply: "ตอบกลับ",
      like: "ถูกใจ",
      dislike: "ไม่ถูกใจ",
      vote: "โหวต",
      isRaining: "ฝนตกในพื้นที่ของคุณหรือไม่?",
      yes: "ใช่",
      no: "ไม่",
      affectedAreas: "พื้นที่ได้รับผลกระทบ",
      reportCondition: "รายงานสภาพปัจจุบัน",
      emailDomain: "อนุญาตเฉพาะอีเมล @satreetrat.ac.th เท่านั้น",
    },
    developer: {
      title: "การตั้งค่านักพัฒนา",
      passwordRequired: "ใส่รหัสผ่านเพื่อเข้าถึงการตั้งค่านักพัฒนา",
      password: "รหัสผ่าน",
      enterPassword: "ใส่รหัสผ่าน",
      authenticate: "ยืนยันตัวตน",
      accessGranted: "เข้าถึงได้",
      accessGrantedDescription: "คุณสามารถแก้ไขการตั้งค่าได้แล้ว",
      accessDenied: "ปฏิเสธการเข้าถึง",
      accessDeniedDescription: "รหัสผ่านไม่ถูกต้อง",
      settings: "การตั้งค่านักพัฒนา",
      settingsDescription: "กำหนดค่า API keys และพารามิเตอร์ระบบ",
      affectedAreasConfig: "การกำหนดค่าพื้นที่ได้รับผลกระทบ",
      affectedAreasDescription: "กำหนดระดับน้ำสำหรับพื้นที่ได้รับผลกระทบต่างๆ",
      areaName: "ชื่อพื้นที่",
      waterLevel: "ระดับน้ำ (ซม.)",
      addArea: "เพิ่มพื้นที่",
      removeArea: "ลบพื้นที่",
      announcement: {
        title: "ระบบประกาศ",
        description: "ส่งประกาศให้ผู้ใช้ทุกคน",
        message: "ข้อความประกาศ",
        placeholder: "ใส่ข้อความประกาศของคุณ...",
        note: "ข้อความนี้จะแสดงให้ผู้ใช้ทุกคนเห็น",
        clear: "ล้างประกาศ",
      },
      waterLevelSettings: "การกำหนดค่าระดับน้ำท่วม",
      waterLevelSettingsDescription: "กำหนดระดับเตือนน้ำท่วมและช่วงเวลาอัปเดต",
      warningLevel: "ระดับเฝ้าระวังน้ำท่วม (ซม.)",
      dangerLevel: "ระดับเตือนน้ำท่วม (ซม.)",
      updateInterval: "ช่วงเวลาอัปเดต (วินาที)",
      cancel: "ยกเลิก",
      saveSettings: "บันทึกการตั้งค่า",
      settingsSaved: "บันทึกการตั้งค่าแล้ว",
      settingsSavedDescription: "การกำหนดค่าได้รับการอัปเดตแล้ว",
    },
    timeUnits: {
      days: "วัน",
      hours: "ชั่วโมง",
      minutes: "นาที",
    },
    common: {
      loading: "กำลังโหลด...",
      error: "ข้อผิดพลาด",
      retry: "ลองใหม่",
      close: "ปิด",
      save: "บันทึก",
      cancel: "ยกเลิก",
      delete: "ลบ",
      edit: "แก้ไข",
      add: "เพิ่ม",
      remove: "ลบ",
      darkMode: "โหมดมืด",
      lightMode: "โหมดสว่าง",
      addLineContact: "เพิ่มติดต่อ LINE",
    },
  },
}

export function useLanguage() {
  return {
    t: translations.en, // Default to English for now, will be updated with context
  }
}
